# -*- coding: utf-8 -*-
"""Story_GPT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tG05xwRVpNH6dS-p9cgajFxEKxqo1hA3
"""

!pip -q install datasets tokenizers tqdm matplotlib

"""## 2) Imports and project folders"""

import os
import math
import json
import random
from dataclasses import dataclass

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

import matplotlib.pyplot as plt
from tqdm.auto import tqdm
from datasets import load_dataset
from tokenizers import Tokenizer, models, trainers, pre_tokenizers, decoders

SEED = 42
random.seed(SEED)
torch.manual_seed(SEED)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", DEVICE)

BASE_DIR = "/content/gpt_project"
DATA_DIR = os.path.join(BASE_DIR, "data")
PRETRAIN_DIR = os.path.join(DATA_DIR, "pretrain")
FINETUNE_DIR = os.path.join(DATA_DIR, "finetune")
TOKENIZER_DIR = os.path.join(BASE_DIR, "tokenizer")
CHECKPOINT_DIR = os.path.join(BASE_DIR, "checkpoints")
RESULTS_DIR = os.path.join(BASE_DIR, "results")

for d in [PRETRAIN_DIR, FINETUNE_DIR, TOKENIZER_DIR, CHECKPOINT_DIR, RESULTS_DIR]:
    os.makedirs(d, exist_ok=True)

print("Folders created.")

"""# 3) Download and prepare pretraining data from TinyStories

This creates:

data/pretrain/data.txt
"""

from datasets import load_dataset

# Load a subset to keep it beginner-friendly and faster
ds = load_dataset("roneneldan/TinyStories", split="train[:5000]")

pretrain_path = os.path.join(PRETRAIN_DIR, "data.txt")

with open(pretrain_path, "w", encoding="utf-8") as f:
    for item in ds:
        text = item["text"].strip().replace("\r", " ")
        f.write(text + "\n\n")

print("Saved pretraining text to:", pretrain_path)
print("File size (MB):", round(os.path.getsize(pretrain_path) / (1024 * 1024), 2))

"""# 4) Prepare simple SFT dataset

This version uses a handmade beginner-friendly SFT set.
You can later replace it with Alpaca if you want.

It creates:

data/finetune/sft_data.jsonl
"""

sft_examples = [
    {"instruction": "Summarize the text.", "input": "The cat sat on the mat and then went to sleep.", "output": "A cat sat on the mat and fell asleep."},
    {"instruction": "Translate to French.", "input": "Good morning.", "output": "Bonjour."},
    {"instruction": "Write a short poem about rain.", "input": "", "output": "Rain taps softly on the ground, whispering a silver sound."},
    {"instruction": "Answer the question.", "input": "What is the capital of France?", "output": "The capital of France is Paris."},
    {"instruction": "Rewrite the sentence in simpler words.", "input": "The child was ecstatic about the excursion.", "output": "The child was very happy about the trip."},
]

# Expand to 200 by repeating patterns with slight changes
more_examples = []
animals = ["cat", "dog", "rabbit", "bird", "fox"]
places = ["park", "garden", "school", "forest", "village"]
actions = ["ran", "jumped", "slept", "played", "sang"]

for i in range(195):
    animal = random.choice(animals)
    place = random.choice(places)
    action = random.choice(actions)

    more_examples.append({
        "instruction": "Summarize the text.",
        "input": f"The {animal} went to the {place}. It {action} there for a while and then returned home happily.",
        "output": f"A {animal} visited the {place}, {action} there, and went home happy."
    })

sft_examples.extend(more_examples)

sft_path = os.path.join(FINETUNE_DIR, "sft_data.jsonl")
with open(sft_path, "w", encoding="utf-8") as f:
    for ex in sft_examples:
        f.write(json.dumps(ex, ensure_ascii=False) + "\n")

print("Saved SFT data to:", sft_path)
print("Number of examples:", len(sft_examples))

"""#5) Train a BPE tokenizer

This creates:

tokenizer/tokenizer.json
"""

tokenizer_path = os.path.join(TOKENIZER_DIR, "tokenizer.json")

tokenizer = Tokenizer(models.BPE(unk_token="[UNK]"))
tokenizer.pre_tokenizer = pre_tokenizers.ByteLevel()
tokenizer.decoder = decoders.ByteLevel()

trainer = trainers.BpeTrainer(
    vocab_size=4000,
    min_frequency=2,
    special_tokens=["[PAD]", "[UNK]", "[BOS]", "[EOS]"]
)

tokenizer.train([pretrain_path], trainer)
tokenizer.save(tokenizer_path)

print("Tokenizer saved to:", tokenizer_path)
print("Vocab size:", tokenizer.get_vocab_size())

"""#6) Load tokenizer and helper functions"""

tokenizer = Tokenizer.from_file(tokenizer_path)

PAD_ID = tokenizer.token_to_id("[PAD]")
UNK_ID = tokenizer.token_to_id("[UNK]")
BOS_ID = tokenizer.token_to_id("[BOS]")
EOS_ID = tokenizer.token_to_id("[EOS]")

def encode_text(text, add_bos=False, add_eos=False):
    ids = tokenizer.encode(text).ids
    if add_bos:
        ids = [BOS_ID] + ids
    if add_eos:
        ids = ids + [EOS_ID]
    return ids

def decode_ids(ids):
    return tokenizer.decode(ids)

"""#7) Read pretraining text and tokenize it"""

with open(pretrain_path, "r", encoding="utf-8") as f:
    text = f.read()

all_ids = encode_text(text, add_bos=False, add_eos=False)
print("Total tokens:", len(all_ids))

split_idx = int(0.9 * len(all_ids))
train_ids = all_ids[:split_idx]
val_ids = all_ids[split_idx:]

print("Train tokens:", len(train_ids))
print("Val tokens:", len(val_ids))

"""#8) Create dataset for pretraining"""

class NextTokenDataset(Dataset):
    def __init__(self, token_ids, block_size):
        self.token_ids = token_ids
        self.block_size = block_size

    def __len__(self):
        return len(self.token_ids) - self.block_size - 1

    def __getitem__(self, idx):
        x = torch.tensor(self.token_ids[idx:idx + self.block_size], dtype=torch.long)
        y = torch.tensor(self.token_ids[idx + 1:idx + self.block_size + 1], dtype=torch.long)
        return x, y

block_size = 128
batch_size = 32

train_dataset = NextTokenDataset(train_ids, block_size)
val_dataset = NextTokenDataset(val_ids, block_size)

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, drop_last=True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, drop_last=True)

print("Train batches:", len(train_loader))
print("Val batches:", len(val_loader))

"""#9) Build GPT model from scratch"""

@dataclass
class GPTConfig:
    vocab_size: int
    block_size: int = 128
    n_embd: int = 128
    n_head: int = 4
    n_layer: int = 4
    dropout: float = 0.1

class CausalSelfAttention(nn.Module):
    def __init__(self, config):
        super().__init__()
        assert config.n_embd % config.n_head == 0

        self.n_head = config.n_head
        self.head_dim = config.n_embd // config.n_head

        self.qkv = nn.Linear(config.n_embd, 3 * config.n_embd)
        self.proj = nn.Linear(config.n_embd, config.n_embd)
        self.attn_dropout = nn.Dropout(config.dropout)
        self.resid_dropout = nn.Dropout(config.dropout)

        mask = torch.tril(torch.ones(config.block_size, config.block_size))
        self.register_buffer("mask", mask.view(1, 1, config.block_size, config.block_size))

    def forward(self, x):
        B, T, C = x.size()
        qkv = self.qkv(x)
        q, k, v = qkv.split(C, dim=2)

        q = q.view(B, T, self.n_head, self.head_dim).transpose(1, 2)
        k = k.view(B, T, self.n_head, self.head_dim).transpose(1, 2)
        v = v.view(B, T, self.n_head, self.head_dim).transpose(1, 2)

        att = (q @ k.transpose(-2, -1)) / math.sqrt(self.head_dim)
        att = att.masked_fill(self.mask[:, :, :T, :T] == 0, float("-inf"))
        att = torch.softmax(att, dim=-1)
        att = self.attn_dropout(att)

        y = att @ v
        y = y.transpose(1, 2).contiguous().view(B, T, C)

        y = self.resid_dropout(self.proj(y))
        return y

class FeedForward(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(config.n_embd, 4 * config.n_embd),
            nn.GELU(),
            nn.Linear(4 * config.n_embd, config.n_embd),
            nn.Dropout(config.dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.ln1 = nn.LayerNorm(config.n_embd)
        self.attn = CausalSelfAttention(config)
        self.ln2 = nn.LayerNorm(config.n_embd)
        self.ffwd = FeedForward(config)

    def forward(self, x):
        x = x + self.attn(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

class GPT(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.config = config

        self.token_emb = nn.Embedding(config.vocab_size, config.n_embd)
        self.pos_emb = nn.Embedding(config.block_size, config.n_embd)
        self.drop = nn.Dropout(config.dropout)

        self.blocks = nn.Sequential(*[Block(config) for _ in range(config.n_layer)])
        self.ln_f = nn.LayerNorm(config.n_embd)
        self.head = nn.Linear(config.n_embd, config.vocab_size, bias=False)

    def forward(self, idx, targets=None):
        B, T = idx.size()
        assert T <= self.config.block_size, "Sequence too long"

        pos = torch.arange(0, T, device=idx.device).unsqueeze(0)
        tok = self.token_emb(idx)
        pos = self.pos_emb(pos)
        x = self.drop(tok + pos)

        x = self.blocks(x)
        x = self.ln_f(x)
        logits = self.head(x)

        loss = None
        if targets is not None:
            loss = nn.functional.cross_entropy(
                logits.view(-1, logits.size(-1)),
                targets.view(-1)
            )

        return logits, loss

    @torch.no_grad()
    def generate(self, idx, max_new_tokens=50, temperature=1.0, top_k=None):
        self.eval()
        for _ in range(max_new_tokens):
            idx_cond = idx[:, -self.config.block_size:]
            logits, _ = self(idx_cond)
            logits = logits[:, -1, :] / temperature

            if top_k is not None:
                v, _ = torch.topk(logits, min(top_k, logits.size(-1)))
                logits[logits < v[:, [-1]]] = -float("inf")

            probs = torch.softmax(logits, dim=-1)
            next_id = torch.multinomial(probs, num_samples=1)
            idx = torch.cat((idx, next_id), dim=1)
        return idx

config = GPTConfig(
    vocab_size=tokenizer.get_vocab_size(),
    block_size=block_size,
    n_embd=128,
    n_head=4,
    n_layer=4,
    dropout=0.1
)

model = GPT(config).to(DEVICE)
print("Model parameters:", sum(p.numel() for p in model.parameters()) / 1e6, "M")

"""#10) Training helpers"""

def evaluate(model, loader, max_batches=100):
    model.eval()
    losses = []
    with torch.no_grad():
        for i, (x, y) in enumerate(loader):
            if i >= max_batches:
                break
            x, y = x.to(DEVICE), y.to(DEVICE)
            _, loss = model(x, y)
            losses.append(loss.item())
    return sum(losses) / len(losses)

def train_model(model, train_loader, val_loader, epochs=3, lr=3e-4, ckpt_name="pretrained.pt"):
    optimizer = torch.optim.AdamW(model.parameters(), lr=lr)
    train_losses = []
    val_losses = []

    for epoch in range(epochs):
        model.train()
        pbar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs}")
        for x, y in pbar:
            x, y = x.to(DEVICE), y.to(DEVICE)

            optimizer.zero_grad()
            _, loss = model(x, y)
            loss.backward()
            optimizer.step()

            train_losses.append(loss.item())
            pbar.set_postfix(loss=loss.item())

        val_loss = evaluate(model, val_loader)
        val_losses.append(val_loss)
        print(f"Epoch {epoch+1}: val_loss = {val_loss:.4f}")

        torch.save(model.state_dict(), os.path.join(CHECKPOINT_DIR, ckpt_name))

    return train_losses, val_losses

"""#11) Pretrain the model"""

pretrain_train_losses, pretrain_val_losses = train_model(
    model,
    train_loader,
    val_loader,
    epochs=3,
    lr=3e-4,
    ckpt_name="pretrained.pt"
)

"""#12) Plot pretraining loss"""

#12
plt.figure(figsize=(10, 4))
plt.plot(pretrain_train_losses, label="train loss")
plt.title("Pretraining Loss")
plt.xlabel("Step")
plt.ylabel("Loss")
plt.legend()
plt.show()

"""# 13) Generate text from pretrained model"""

#13
def generate_text(prompt, max_new_tokens=80):
    ids = encode_text(prompt, add_bos=False, add_eos=False)
    x = torch.tensor([ids], dtype=torch.long).to(DEVICE)

    with torch.no_grad():
        out = model.generate(x, max_new_tokens=max_new_tokens, temperature=0.9, top_k=40)

    return decode_ids(out[0].tolist())

prompts = [
    "Once upon a time",
    "The little dog",
    "In a small town"
]

for p in prompts:
    print("=" * 80)
    print("PROMPT:", p)
    print(generate_text(p, max_new_tokens=60))
    print()

"""#14) Convert SFT JSONL into training text

We now turn each example into this format:

Instruction

Input

Response
"""

#14
def format_sft_example(ex):
    instruction = ex["instruction"].strip()
    input_text = ex.get("input", "").strip()
    output = ex["output"].strip()

    return (
        f"### Instruction:\n{instruction}\n\n"
        f"### Input:\n{input_text}\n\n"
        f"### Response:\n{output}"
    )

with open(sft_path, "r", encoding="utf-8") as f:
    sft_data = [json.loads(line) for line in f]

formatted_sft = [format_sft_example(ex) for ex in sft_data]

print(formatted_sft[0])

"""#15) Tokenize SFT data"""

#15
sft_token_ids = []
for text in formatted_sft:
    ids = encode_text(text, add_bos=True, add_eos=True)
    sft_token_ids.extend(ids + [EOS_ID])

print("Total SFT tokens:", len(sft_token_ids))

split_idx = int(0.9 * len(sft_token_ids))
sft_train_ids = sft_token_ids[:split_idx]
sft_val_ids = sft_token_ids[split_idx:]

sft_train_dataset = NextTokenDataset(sft_train_ids, block_size)
sft_val_dataset = NextTokenDataset(sft_val_ids, block_size)

sft_train_loader = DataLoader(sft_train_dataset, batch_size=16, shuffle=True, drop_last=True)
sft_val_loader = DataLoader(sft_val_dataset, batch_size=16, shuffle=False, drop_last=True)

print("SFT train batches:", len(sft_train_loader))
print("SFT val batches:", len(sft_val_loader))

"""#16) Fine-tune the pretrained model"""

#16
finetune_train_losses, finetune_val_losses = train_model(
    model,
    sft_train_loader,
    sft_val_loader,
    epochs=3,
    lr=1e-4,
    ckpt_name="finetuned.pt"
)

"""#17) Plot fine-tuning loss"""

#17
plt.figure(figsize=(10, 4))
plt.plot(finetune_train_losses, label="train loss")
plt.title("Fine-tuning Loss")
plt.xlabel("Step")
plt.ylabel("Loss")
plt.legend()
plt.show()

"""#18) Test instruction following"""

#18
def build_instruction_prompt(instruction, input_text=""):
    return (
        f"### Instruction:\n{instruction}\n\n"
        f"### Input:\n{input_text}\n\n"
        f"### Response:\n"
    )

test_prompts = [
    ("Summarize the text.", "The boy went to the river and played with his friends all afternoon."),
    ("Answer the question.", "What is the capital of Germany?"),
    ("Write a short poem about the moon.", ""),
    ("Rewrite the sentence in simpler words.", "The child was exhausted after the excursion.")
]

for inst, inp in test_prompts:
    prompt = build_instruction_prompt(inst, inp)
    ids = encode_text(prompt)
    x = torch.tensor([ids], dtype=torch.long).to(DEVICE)

    with torch.no_grad():
        out = model.generate(x, max_new_tokens=50, temperature=0.8, top_k=40)

    text = decode_ids(out[0].tolist())
    print("=" * 80)
    print(text)
    print()

"""#19) Compute simple perplexity"""

#19
val_loss = evaluate(model, sft_val_loader)
perplexity = math.exp(val_loss)

print("Validation loss:", val_loss)
print("Perplexity:", perplexity)

"""#20) Save sample outputs to files"""

#20
samples_path = os.path.join(RESULTS_DIR, "samples.txt")

with open(samples_path, "w", encoding="utf-8") as f:
    for inst, inp in test_prompts:
        prompt = build_instruction_prompt(inst, inp)
        ids = encode_text(prompt)
        x = torch.tensor([ids], dtype=torch.long).to(DEVICE)

        with torch.no_grad():
            out = model.generate(x, max_new_tokens=50, temperature=0.8, top_k=40)

        text = decode_ids(out[0].tolist())
        f.write("=" * 80 + "\n")
        f.write(text + "\n\n")

print("Saved generated samples to:", samples_path)

"""#21) Save final config for report"""

#21
run_info = {
    "device": DEVICE,
    "vocab_size": config.vocab_size,
    "block_size": config.block_size,
    "n_embd": config.n_embd,
    "n_head": config.n_head,
    "n_layer": config.n_layer,
    "dropout": config.dropout,
    "pretrain_epochs": 3,
    "finetune_epochs": 3,
}

with open(os.path.join(RESULTS_DIR, "run_info.json"), "w", encoding="utf-8") as f:
    json.dump(run_info, f, indent=2)

print("Saved run info.")

"""#22)Evaluation"""

import math
import torch

def evaluate_with_perplexity(model, loader, device, max_batches=None):
    model.eval()
    losses = []

    with torch.no_grad():
        for i, (x, y) in enumerate(loader):
            if max_batches is not None and i >= max_batches:
                break

            x = x.to(device)
            y = y.to(device)

            _, loss = model(x, y)
            losses.append(loss.item())

    avg_loss = sum(losses) / len(losses)
    perplexity = math.exp(avg_loss)

    return avg_loss, perplexity


val_loss, perplexity = evaluate_with_perplexity(
    model=model,
    loader=sft_val_loader,
    device=DEVICE
)

print("-" * 40)
print("Model Evaluation Metrics:")
print(f"Final Loss: {val_loss:.3f}")
print(f"Perplexity: {perplexity:.2f}")
print("-" * 40)

"""#24)emo"""

!pip -q install gradio

import os
import torch
import gradio as gr

BASE_DIR = "/content/gpt_project"
TOKENIZER_PATH = os.path.join(BASE_DIR, "tokenizer", "tokenizer.json")
MODEL_PATH = os.path.join(BASE_DIR, "checkpoints", "finetuned.pt")
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

import math
import torch
import torch.nn as nn
from dataclasses import dataclass

@dataclass
class GPTConfig:
    vocab_size: int
    block_size: int = 128
    n_embd: int = 128
    n_head: int = 4
    n_layer: int = 4
    dropout: float = 0.1


class CausalSelfAttention(nn.Module):
    def __init__(self, config):
        super().__init__()
        assert config.n_embd % config.n_head == 0, "n_embd must be divisible by n_head"

        self.n_head = config.n_head
        self.head_dim = config.n_embd // config.n_head

        self.qkv = nn.Linear(config.n_embd, 3 * config.n_embd)
        self.proj = nn.Linear(config.n_embd, config.n_embd)

        self.attn_dropout = nn.Dropout(config.dropout)
        self.resid_dropout = nn.Dropout(config.dropout)

        mask = torch.tril(torch.ones(config.block_size, config.block_size))
        self.register_buffer("mask", mask.view(1, 1, config.block_size, config.block_size))

    def forward(self, x):
        B, T, C = x.size()

        qkv = self.qkv(x)          # (B, T, 3C)
        q, k, v = qkv.split(C, dim=2)

        q = q.view(B, T, self.n_head, self.head_dim).transpose(1, 2)  # (B, nh, T, hs)
        k = k.view(B, T, self.n_head, self.head_dim).transpose(1, 2)
        v = v.view(B, T, self.n_head, self.head_dim).transpose(1, 2)

        att = (q @ k.transpose(-2, -1)) / math.sqrt(self.head_dim)     # (B, nh, T, T)
        att = att.masked_fill(self.mask[:, :, :T, :T] == 0, float("-inf"))
        att = torch.softmax(att, dim=-1)
        att = self.attn_dropout(att)

        y = att @ v                                                    # (B, nh, T, hs)
        y = y.transpose(1, 2).contiguous().view(B, T, C)              # (B, T, C)

        y = self.proj(y)
        y = self.resid_dropout(y)
        return y


class FeedForward(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(config.n_embd, 4 * config.n_embd),
            nn.GELU(),
            nn.Linear(4 * config.n_embd, config.n_embd),
            nn.Dropout(config.dropout),
        )

    def forward(self, x):
        return self.net(x)


class Block(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.ln1 = nn.LayerNorm(config.n_embd)
        self.attn = CausalSelfAttention(config)
        self.ln2 = nn.LayerNorm(config.n_embd)
        self.ffwd = FeedForward(config)

    def forward(self, x):
        x = x + self.attn(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x


class GPT(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.config = config

        self.token_emb = nn.Embedding(config.vocab_size, config.n_embd)
        self.pos_emb = nn.Embedding(config.block_size, config.n_embd)
        self.drop = nn.Dropout(config.dropout)

        self.blocks = nn.Sequential(*[Block(config) for _ in range(config.n_layer)])
        self.ln_f = nn.LayerNorm(config.n_embd)
        self.head = nn.Linear(config.n_embd, config.vocab_size, bias=False)

    def forward(self, idx, targets=None):
        B, T = idx.size()
        if T > self.config.block_size:
            raise ValueError(f"Sequence length {T} exceeds block size {self.config.block_size}")

        pos = torch.arange(0, T, device=idx.device).unsqueeze(0)  # (1, T)

        tok_emb = self.token_emb(idx)   # (B, T, C)
        pos_emb = self.pos_emb(pos)     # (1, T, C)
        x = self.drop(tok_emb + pos_emb)

        x = self.blocks(x)
        x = self.ln_f(x)
        logits = self.head(x)           # (B, T, vocab_size)

        loss = None
        if targets is not None:
            loss = nn.functional.cross_entropy(
                logits.view(-1, logits.size(-1)),
                targets.view(-1)
            )

        return logits, loss

    @torch.no_grad()
    def generate(self, idx, max_new_tokens=60, temperature=0.8, top_k=40):
        self.eval()

        for _ in range(max_new_tokens):
            idx_cond = idx[:, -self.config.block_size:]
            logits, _ = self(idx_cond)

            logits = logits[:, -1, :] / temperature

            if top_k is not None:
                v, _ = torch.topk(logits, min(top_k, logits.size(-1)))
                logits[logits < v[:, [-1]]] = -float("inf")

            probs = torch.softmax(logits, dim=-1)
            next_id = torch.multinomial(probs, num_samples=1)
            idx = torch.cat((idx, next_id), dim=1)

        return idx

from tokenizers import Tokenizer

tokenizer = Tokenizer.from_file(TOKENIZER_PATH)

PAD_ID = tokenizer.token_to_id("[PAD]")
UNK_ID = tokenizer.token_to_id("[UNK]")
BOS_ID = tokenizer.token_to_id("[BOS]")
EOS_ID = tokenizer.token_to_id("[EOS]")

def encode_text(text, add_bos=False, add_eos=False):
    ids = tokenizer.encode(text).ids
    if add_bos:
        ids = [BOS_ID] + ids
    if add_eos:
        ids = ids + [EOS_ID]
    return ids

def decode_ids(ids):
    return tokenizer.decode(ids)

config = GPTConfig(
    vocab_size=tokenizer.get_vocab_size(),
    block_size=128,
    n_embd=128,
    n_head=4,
    n_layer=4,
    dropout=0.1
)

model = GPT(config).to(DEVICE)
model.load_state_dict(torch.load(MODEL_PATH, map_location=DEVICE))
model.eval()
print("Loaded.")

def build_instruction_prompt(instruction, input_text=""):
    return (
        f"### Instruction:\n{instruction}\n\n"
        f"### Input:\n{input_text}\n\n"
        f"### Response:\n"
    )

def generate_response(instruction, input_text, max_new_tokens, temperature):
    prompt = build_instruction_prompt(instruction, input_text)
    ids = encode_text(prompt)

    x = torch.tensor([ids], dtype=torch.long).to(DEVICE)

    with torch.no_grad():
        out = model.generate(
            x,
            max_new_tokens=int(max_new_tokens),
            temperature=float(temperature),
            top_k=40
        )

    full_text = decode_ids(out[0].tolist())

    if "### Response:" in full_text:
        return full_text.split("### Response:")[-1].strip()
    return full_text

with gr.Blocks() as demo:
    gr.Markdown("# GPT From Scratch Mini Demo")

    instruction = gr.Textbox(label="Instruction")
    input_text = gr.Textbox(label="Input")
    max_new_tokens = gr.Slider(20, 150, value=60, step=1, label="Max New Tokens")
    temperature = gr.Slider(0.2, 1.5, value=0.8, step=0.1, label="Temperature")
    output = gr.Textbox(label="Model Output", lines=10)

    btn = gr.Button("Generate")
    btn.click(
        fn=generate_response,
        inputs=[instruction, input_text, max_new_tokens, temperature],
        outputs=output
    )

demo.launch(share=True)